FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY web_interface.py .

EXPOSE 8012

CMD ["python", "web_interface.py", "--port", "8012"]